%YAML:1.0

#camera calibration 
model_type: PINHOLE
camera_name: slave1
# Note: considers only projection matrix assuming that the images (keyframes from okvis) are pre-rectifed
projection_matrix:
    fx: 1.0579968843349914e+03
    fy: 1.0579968843349914e+03
    cx: 7.5429498291015625e+02
    cy: 5.8656024932861328e+02
#image resize factor. Note that, this factor MUST be same as OKVIS config file
resizeFactor: 0.5

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#loop closure parameters
loop_closure: 1

min_loop_num: 40


