%YAML:1.0

#camera calibration 
model_type: PINHOLE
camera_name: cam_fl

#image resize factor. Note that, this factor MUST be same as OKVIS config file
resizeFactor: 0.5

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

fast_relocalization: 1
loop_closure_params:
    enable: 1  
    min_correspondences: 25
    pnp_reprojection_threshold: 10.0
    pnp_ransac_iterations: 100

#For uber estimator
health:
    enable: 1
    min_keypoints: 10
    consecutive_keyframes: 3
    keyframe_wait_time: 2
    kps_per_quadrant: 1

# if enabled will save debug images in pose_graph/output_logs/
debug_image: 0

# The left camera params
height: 1200
width: 1600
distortion_coeffs: [-0.2738091509104935, 0.06880880935804803, -0.000527464769387835, -0.00222003600101452]
focal_length: [899.7164677811579, 897.0584781993765] 
principal_point: [775.6342844800996, 565.3621248822564]

# To transform pose between uber and okvis coordinate systems
T_SC: [-0.05832554, -0.49729442, 0.86561908, 0.4404166,
        0.99825455, -0.02099889, 0.05519876, -0.04791664,
        -0.009273, 0.86732768, 0.49765118, -0.02872042,
        0.0, 0.0, 0.0, 1.0]
T_BS: [1.0, 0.0, 0.0, 0.0,
      0.0, -1.0, 0.0, 0.0,
      0.0, 0.0, -1.0, 0.0,
      0.0, 0.0, 0.0, 1.0]

#to synchronize keyframe and raw images. This should be same as okvis config file
image_delay: 0.0 
#minimum landmark quality to be added to global
min_landmark_quality: 0.001
