%YAML:1.0

#camera calibration 
model_type: PINHOLE
camera_name: gopro

projection_matrix:
   fx: 582.7585362687838
   fy: 580.8446349178992
   cx: 479.95702656023155
   cy: 271.8298929212255

#image resize factor. Note that, this factor MUST be same as OKVIS config file
resizeFactor: 1.0

#optimization parameters
max_solver_time: 0.1  # max solver itration time (ms), to guarantee real time
max_num_iterations: 100   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#loop closure parameters
loop_closure: 1   #if you want to use loop closure to minimize the drift, set loop_closure true and give your brief pattern file path and vocabulary file path accordingly;
                     #also give the camera calibration file same as feature_tracker node
fast_relocalization: 1
min_loop_num: 20


# Added by Bharat
# Parameters for color mapping as we need to subscribe to original color image
is_stereo: 0
cam0:
    width: 960
    height: 540
    D: [-0.1150974141409347, 0.10292772047643643, 0.001419836324816038, -0.0018379214527896284]
