%YAML:1.0

#camera calibration 
model_type: PINHOLE
camera_name: gopro
# Note: considers only projection matrix assuming that the images (keyframes from okvis) are pre-rectifed
# projection_matrix:
#    fx: 608.7746670346972
#    fy: 608.2164297233925
#    cx: 487.25241330522186
#    cy: 263.05259862794196

projection_matrix:
   fx: 583.16116134
   fy: 581.292988
   cx: 481.92859774
   cy: 270.2504108

#image resize factor. Note that, this factor MUST be same as OKVIS config file
resizeFactor: 1.0

#optimization parameters
max_solver_time: 0.1  # max solver itration time (ms), to guarantee real time
max_num_iterations: 100   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#loop closure parameters
loop_closure: 1   #if you want to use loop closure to minimize the drift, set loop_closure true and give your brief pattern file path and vocabulary file path accordingly;
                     #also give the camera calibration file same as feature_tracker node
fast_relocalization: 1
min_loop_num: 20


is_stereo: 0
cam0:
    width: 960
    height: 540
    D: [-0.10973803,  0.09313709,  0.00143941,  0.0004831]