%YAML:1.0

#camera calibration 
model_type: PINHOLE
camera_name: slave1
# Note: considers only projection matrix assuming that the images (keyframes from okvis) are pre-rectifed
projection_matrix:
    fx: 1146.5925232
    fy: 1146.5925232
    cx: 773.8216629
    cy: 578.06917572

#image resize factor. Note that, this factor MUST be same as OKVIS config file
resizeFactor: 0.5

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

fast_relocalization: 1

#loop closure 
#if you want to use loop closure to minimize the drift, set loop_closure true and give your brief pattern file path and vocabulary file path accordingly;
#also give the camera calibration file same as feature_tracker node
loop_closure_params:
    enable: 1  
    min_correspondences: 25
    pnp_reprojection_threshold: 25.0     

health:
    enable: 0
    min_keypoints: 15
    consecutive_keyframes: 3
    keyframe_wait_time: 2.0
    kps_per_quadrant: 1

debug_image: 1

# For undistorting original color image
is_stereo: 1
cam0:
    height: 1200
    width: 1600
    D: [-0.16012168, 0.1020015, 0.00369027, 0.0034287]
    K: [1149.52000993, 0.0, 798.75530924,
        0.0, 1150.57923685, 577.20248548,
        0.0, 0.0, 1.0]
    R: [0.99981503, -0.00405723, 0.01880029,
        0.00376565, 0.99987248, 0.01551934,
        -0.01886086, -0.01544568, 0.99970281]

#R is rectification matrix
#to synchronize keyframe and raw images. This should be same as okvis config file
image_delay: 0.0 
#minimum landmark quality to be added to global
min_landmark_quality: 0.01
